#!/usr/bin/env python

import os
os.environ['DISPLAY'] = ':0'

import pygtk
pygtk.require('2.0')
import pynotify
import sys
import socket
import re

if __name__ == '__main__':
    if not pynotify.init("Markup"):
        sys.exit(1)

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(("graph.no", 23))

    b = s.recv(1024)
    l = len(b)
    while l > 0:
        r = s.recv(1024)
        b = b + r
        l = len(r)

    coffee = re.search('([0-9\.]+ grams)', b).group(0)

    if os.path.exists('/tmp/coffee'):
        oldcoffee = float(open('/tmp/coffee').readline().rstrip())
    else:
        oldcoffee = -10000

    coffeeint = float(coffee.split(' ')[0])
    diff = oldcoffee - coffeeint
    if diff > 100 or diff < -100:
        n = pynotify.Notification("Coffee alert", coffee, "dialog-warning")

        if not n.show():
            print "Failed to send notification"
            sys.exit(1)
        open('/tmp/coffee', 'w').write(str(coffeeint))
