#!/bin/bash

scale=/tmp/scale
calibrate=/tmp/calibrate

# sudo ln -s /home/larsfp/bin/munin-scale.sh /etc/munin/plugins/scale

case $1 in
   config)
        echo "graph_title Weight"
        echo "graph_vlabel grams"
        echo "weight.label weight"
#       cat <<'EOM'
#       graph_title Weight
#       graph_vlabel grams
#       weight.label weight
#EOM
#       system.label system
#       system.draw AREA
#       system.min 0
#       system.type DERIVE
#       system.info CPU time spent by the kernel in system activities

        exit 0
esac

echo -n "weight.value "
cat $scale

exit 0

